services:
  app:
    build: .
    container_name: nestjs-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - STORAGE_ENDPOINT_URL=${STORAGE_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_REGION=${MINIO_REGION}
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: 'AS-built_owner'
      POSTGRES_PASSWORD: 'w0ditQAYpOr7'
      POSTGRES_DB: 'AS-built'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pgdata:
    driver: local
