name: Node.js CD

on:
  workflow_run:
    workflows: ['Node.js CI']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment variables
        run: |
          echo "SSH_HOSTNAME: ${{ env.SSH_HOSTNAME }}"  # Use env if it's a normal environment variable
          echo "SSH_USERNAME: ${{ env.SSH_USERNAME }}"  # Use env if it's a normal environment variable
          # If using secrets, then change to secrets
          # echo "SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}"
          # echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"


      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOSTNAME }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/as-built-backend
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:80 ghcr.io/${{ github.repository }}:latest
