name: Node.js CD

on:
  workflow_run:
    workflows: ['Node.js CI']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment variables
        run: |
          echo "SSH_HOSTNAME: ${{ vars.SSH_HOSTNAME }}" 
          echo "SSH_USERNAME: ${{ vars.SSH_USERNAME }}"


      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.SSH_HOSTNAME }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 80:80 ghcr.io/${{ github.repository }}:latest
